window.global =
  shoot_quill: ->
    quill_selector = '#quill-editor'
    target = $(quill_selector).closest('form').find('.text')
    console.log(target)
    window.quill = new Quill(quill_selector,
      modules: toolbar: true
      theme: 'snow')
    window.quill.target = target

    window.quill.on 'text-change', (delta, oldDelta, source) ->
      window.quill.target.text(JSON.stringify(delta))
      return

    # # ---
    # # generated by js2coffee 2.2.0

    # $("#{quill_selector} form").on 'submit', ->
    #   contents = window.quill.getContents()
    #   contents = JSON.stringify(contents)
    #   target_field = @find('textarea.text')
    #   target_field.text(contents)
    #   return


$(document).ready(global.shoot_quill)